### ISSUE TITLE
Añadir más sonidos

### ISSUE THREAD

**Issue by elraro** [elraro/rajoyBot#14]
Añadir más frases graciosas de nuestro ex-presidente.

Un mínimo de calidad, por favor :)

Las frases se deben convertir a ogg con el siguiente comando:

```
ffmpeg -i sonido.mp3 -map_metadata -1 -c:a libopus -b:a 64k -vbr on -compression_level 10 sonido.ogg
```

**Comment by dmcallejo** [comment]
hdp
