### ISSUE TITLE
Nueva frase

### ISSUE THREAD

**Issue by palonsoro** [elraro/rajoyBot#33]
Creo que añadir esta nueva perla hará que el bot esté dentro de un orden y por tanto en equilibrio:

https://twitter.com/Erik_Urano/status/1676697529461743622

¡Gracias!

**Comment by elraro** [comment]
Gracias @palonsoro cuando llegue el Hacktoberfest implementamos la frase.

**Comment by elraro** [comment]
Agregada. https://github.com/elraro/rajoyBot/pull/36

Gracias!

**Comment by palonsoro** [comment]
A ti
