### ISSUE TITLE
Otra frase nueva

### ISSUE THREAD

**Issue by palonsoro** [elraro/rajoyBot#34]
https://twitter.com/diostuitero/status/1679864427422597122?s=48&t=vr9L13TJQLwhdO6U3aF2eQ

Con esta ya no sé ni qué broma hacer. Solo que merece estar en el bot :laughing:

**Comment by elraro** [comment]
Para hacktoberfest :P gracias!

**Comment by elraro** [comment]
https://github.com/elraro/rajoyBot/pull/35

Implementada!

**Comment by palonsoro** [comment]
Gracias
